import { Post } from "@/types";


export const INITIAL_POSTS: Post[] = [
  {
    id: "1",
    author: "Luiza Nogueira",
    initials: "LN",
    role: "Leitor · Entrelinhas",
    time: "há 18 min",
    text: "Voltei a uma passagem de A paixão segundo G.H. e fiquei pensando como certos livros não querem ser entendidos de uma vez. Eles pedem convivência.",
    quote: "A vida se me é, e eu não entendo.",
    book: "A paixão segundo G.H. · Clarice Lispector",
    likes: 24,
    comments: 6,
    reposts: 2,
    isLiked: false,
    isSaved: false,
  },
  {
    id: "2",
    author: "Marcos Prado",
    initials: "MP",
    role: "Leitor · Entrelinhas",
    time: "há 2 h",
    text: "Terminei O Estrangeiro. Camus não me convenceu do absurdo — ele me convenceu da indiferença, que é bem mais difícil de encarar.",
    book: "O Estrangeiro · Albert Camus",
    likes: 41,
    comments: 12,
    reposts: 5,
    isLiked: false,
    isSaved: true,
  },
  {
    id: "3",
    author: "Ana Beatriz",
    initials: "AB",
    role: "Leitor · Entrelinhas",
    time: "ontem",
    text: "Comecei A República hoje. A pergunta que abre o livro é simples e continua sem resposta: o que é ser justo quando ninguém está olhando?",
    quote: "A justiça é a virtude da alma.",
    book: "A República · Platão",
    likes: 63,
    comments: 19,
    reposts: 8,
    isLiked: true,
    isSaved: false,
  },
  {
    id: "4",
    author: "Rafael Lima",
    initials: "RL",
    role: "Leitor · Entrelinhas",
    time: "há 2 dias",
    text: "Nietzsche tem esse dom de te deixar irritado e lúcido ao mesmo tempo. Anotei três páginas inteiras hoje.",
    book: "Além do Bem e do Mal · Friedrich Nietzsche",
    likes: 37,
    comments: 9,
    reposts: 3,
    isLiked: false,
    isSaved: false,
  },
];
